// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArgQ9UgRP1LKhlh_Uu4cUToyrrqhi9J-4',
    appId: '1:426568631045:web:0fae3c7eb2382026642d6c',
    messagingSenderId: '426568631045',
    projectId: 'dashmesh-mechanix',
    authDomain: 'dashmesh-mechanix.firebaseapp.com',
    storageBucket: 'dashmesh-mechanix.appspot.com',
    measurementId: 'G-0KR9PKKFR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwwO-xjnmH2BTb5WlC12va8sgrTiHTMkY',
    appId: '1:426568631045:android:745c21d158fdf506642d6c',
    messagingSenderId: '426568631045',
    projectId: 'dashmesh-mechanix',
    storageBucket: 'dashmesh-mechanix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOD7eEQ187wtLXvNd6re3JVsj9mYg-sbE',
    appId: '1:426568631045:ios:ccda4f894b7a5c16642d6c',
    messagingSenderId: '426568631045',
    projectId: 'dashmesh-mechanix',
    storageBucket: 'dashmesh-mechanix.appspot.com',
    iosBundleId: 'com.example.dashmeshRo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOD7eEQ187wtLXvNd6re3JVsj9mYg-sbE',
    appId: '1:426568631045:ios:ccda4f894b7a5c16642d6c',
    messagingSenderId: '426568631045',
    projectId: 'dashmesh-mechanix',
    storageBucket: 'dashmesh-mechanix.appspot.com',
    iosBundleId: 'com.example.dashmeshRo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArgQ9UgRP1LKhlh_Uu4cUToyrrqhi9J-4',
    appId: '1:426568631045:web:d4374ec17ce77762642d6c',
    messagingSenderId: '426568631045',
    projectId: 'dashmesh-mechanix',
    authDomain: 'dashmesh-mechanix.firebaseapp.com',
    storageBucket: 'dashmesh-mechanix.appspot.com',
    measurementId: 'G-CW3QYXBZG9',
  );
}
